FROM python:3.10-slim

WORKDIR /opt/dagster/app
ENV DAGSTER_HOME=/opt/dagster/app

COPY . .

RUN pip install .

ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG DATABASE_SSL_MODE
ARG CONSUMER_API_KEY
ARG CONSUMER_API_KEY_SECRET
ARG ACCESS_TOKEN
ARG ACCESS_SECRET

ENV DB_HOST $DATABASE_HOST
ENV DB_NAME $DATABASE_NAME
ENV DB_USER $DATABASE_USER
ENV DB_PASSWORD $DATABASE_PASSWORD
ENV DB_PORT DATABASE_PORT
ENV DB_SSL_MODE DATABASE_SSL_MODE
ENV CONSUMER_API_KEY $CONSUMER_API_KEY
ENV CONSUMER_API_KEY_SECRET $CONSUMER_API_KEY_SECRET
ENV ACCESS_TOKEN $ACCESS_TOKEN
ENV ACCESS_SECRET $ACCESS_SECRET

EXPOSE 3000

CMD ["dagster-webserver", "-w", "workspace.yaml", "-h", "0.0.0.0", "-p", "3000"]