services:
  dagster-dagit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'dagster-daemon run'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=5432

  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dagster-postgres:/var/lib/postgresql/data

volumes:
  dagster-postgres:
    driver: local
